### ISSUE TITLE
Elevator action glitch

### ISSUE THREAD

**Issue by MunkyBunky** [MiSTer-devel/Arcade-TaitoSystemSJ_MiSTer#3]
Elevator action the main character is half a character and when you start the games numbers slide down the right hand side and some baddies have half of them as numbers 
![IMG_9970](https://github.com/MiSTer-devel/Arcade-TaitoSystemSJ_MiSTer/assets/137648020/7ff00452-e4a8-45c2-9931-5e04b6edc728)

**Comment by rittwage** [comment]
Mine is glitchy on the right side of all sprites.
![20230625_174912](https://github.com/MiSTer-devel/Arcade-TaitoSystemSJ_MiSTer/assets/122463816/97148a4e-8d0d-4c23-8136-2992bfe6efc9)

**Comment by antongale** [comment]
This issue should be resolved with Arcade-TaitoSJ_20230626.rbf
